//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Addon.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Addon.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First panel description.
        /// </summary>
        public static string GeneralRibbonPanel_Description {
            get {
                return ResourceManager.GetString("GeneralRibbonPanel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General tools.
        /// </summary>
        public static string GeneralRibbonPanel_Text {
            get {
                return ResourceManager.GetString("GeneralRibbonPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show information about the plugin and its authors.
        /// </summary>
        public static string MiscRibbonPanel_AboutButton_Description {
            get {
                return ResourceManager.GetString("MiscRibbonPanel_AboutButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string MiscRibbonPanel_AboutButton_Text {
            get {
                return ResourceManager.GetString("MiscRibbonPanel_AboutButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Miscellaneous tools.
        /// </summary>
        public static string MiscRibbonPanel_Description {
            get {
                return ResourceManager.GetString("MiscRibbonPanel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings description.
        /// </summary>
        public static string MiscRibbonPanel_SettingsButton_Description {
            get {
                return ResourceManager.GetString("MiscRibbonPanel_SettingsButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MiscRibbonPanel_SettingsButton_Text {
            get {
                return ResourceManager.GetString("MiscRibbonPanel_SettingsButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Miscellaneous.
        /// </summary>
        public static string MiscRibbonPanel_Text {
            get {
                return ResourceManager.GetString("MiscRibbonPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check exist new version of current plugin.
        /// </summary>
        public static string MiscRibbonPanel_UpdateButton_Description {
            get {
                return ResourceManager.GetString("MiscRibbonPanel_UpdateButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check update.
        /// </summary>
        public static string MiscRibbonPanel_UpdateButton_Text {
            get {
                return ResourceManager.GetString("MiscRibbonPanel_UpdateButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EDEC.
        /// </summary>
        public static string RibbonTab_Text {
            get {
                return ResourceManager.GetString("RibbonTab_Text", resourceCulture);
            }
        }
    }
}
